extends:
  - vazco/prettier

env:
  jest: true

rules:
  react/display-name: 1
  react/no-this-in-sfc: 2
  valid-jsdoc: 0
  prettier/prettier:
    - error
    - bracketSpacing: false
      printWidth: 80
      singleQuote: true
      tabWidth: 2
      trailingComma: es5

globals:
  __DEV__: false
